# fitness: 46312

"""
Pure empirical compression: mine ALL frequent patterns from sample_submission.

Unlike sol01 which only looked for mathematical identities (commutators, etc.),
this approach mines ANY pattern that appears frequently and was compressible
in the sample paths, without requiring mathematical proof of identity.

The hypothesis: the test set was generated by random walks, so many sequences
will appear that were compressed during generation. We find those.
"""

from collections import Counter, defaultdict
from helpers.core import (
    load_test,
    load_sample_submission_paths,
    apply_path,
    is_solved,
    solved_state,
    GENERATOR_NAMES,
)


def entrypoint() -> dict:
    tests = load_test(proxy=True)
    sample_paths = load_sample_submission_paths()

    rules = _mine_frequent_patterns(sample_paths)
    print(f"Mined {len(rules)} frequent patterns")

    compressed = {}
    for sid, state in tests.items():
        original = sample_paths.get(sid, "")
        compressed_sid = _compress_path(original, rules)
        if is_solved(apply_path(state, compressed_sid)):
            compressed[sid] = compressed_sid
        else:
            compressed[sid] = original

    return compressed


def _mine_frequent_patterns(sample_paths: dict) -> dict:
    """Mine patterns that were compressible in sample_submission."""
    SOLVED = solved_state()

    # Count all subsequences of length 2-6
    subseq_counts = Counter()
    # Track which subsequences appeared at least once
    subseq_in_paths = defaultdict(list)

    for path in sample_paths.values():
        if not path:
            continue
        moves = path.split('.')
        for start in range(len(moves)):
            for length in range(2, 7):
                if start + length > len(moves):
                    break
                subseq = tuple(moves[start:start+length])
                subseq_str = '.'.join(subseq)
                subseq_counts[subseq_str] += 1
                subseq_in_paths[subseq_str].append(path)

    # For each frequent pattern, check if replacing it with shorter made sense
    # i.e., was the original path longer than necessary?
    rules = {}
    min_count = 5

    for pattern_str, count in subseq_counts.items():
        if count < min_count:
            continue
        pattern = tuple(pattern_str.split('.'))
        if len(pattern) < 3:
            continue

        # Check if this pattern can be reduced by basic cancellation
        # If the pattern itself has X.-X, it can be compressed
        compressed = _cancel_moves(list(pattern))
        if len(compressed) < len(pattern):
            # The pattern contains internal cancellation
            # Rule: pattern -> compressed
            if len(pattern) - len(compressed) >= 1:
                # Verify the compressed form has the same effect
                try:
                    pattern_effect = apply_path(SOLVED, pattern_str)
                    compressed_str = '.'.join(compressed)
                    compressed_effect = apply_path(SOLVED, compressed_str)
                    if pattern_effect == compressed_effect:
                        rules[pattern] = tuple(compressed)
                except:
                    pass

    return rules


def _compress_path(path: str, rules: dict) -> str:
    """Apply compression rules iteratively."""
    if not path:
        return path

    # Sort rules by savings (most savings first)
    sorted_rules = sorted(rules.keys(), key=lambda p: len(p) - len(rules[p]), reverse=True)

    max_passes = 50
    for _ in range(max_passes):
        prev = path
        moves = path.split('.')
        moves = [m for m in moves if m]
        moves = _cancel_moves(moves)
        moves = _apply_rules_all(moves, sorted_rules, rules)
        path = '.'.join(moves)
        if path == prev:
            break

    return path


def _apply_rules_all(moves: list, sorted_rules: list, rules: dict) -> list:
    """Apply all rules in sequence (like sol01)."""
    for pattern in sorted_rules:
        replacement = rules[pattern]
        moves = _apply_single_rule(moves, pattern, replacement)
    return moves


def _apply_single_rule(moves: list, pattern: tuple, replacement: tuple) -> list:
    """Apply one rule (pattern -> replacement) to the entire move list."""
    if not pattern or not moves:
        return moves
    pattern_len = len(pattern)
    result = []
    i = 0
    while i < len(moves):
        if i + pattern_len <= len(moves):
            window = tuple(moves[i:i + pattern_len])
            if window == pattern:
                result.extend(replacement)
                i += pattern_len
                continue
        result.append(moves[i])
        i += 1
    return result


def _cancel_moves(moves: list) -> list:
    """Standard X.-X cancellation."""
    stack = []
    for m in moves:
        if not m:
            continue
        if stack and stack[-1] == _inverse(m):
            stack.pop()
        else:
            stack.append(m)
    return stack


def _inverse(move: str) -> str:
    if move.startswith('-'):
        return move[1:]
    return f'-{move}'